executable = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/inference_gnn.sh
output = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/inference_gnn.$(CLUSTER).out
error  = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/inference_gnn.$(CLUSTER).err
log    = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/inference_gnn.$(CLUSTER).log
request_gpus = 1
+MaxRuntime = 86400
notification = Always
queue
