executable = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/inference_run1_signal.sh
output = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/inference_run1_signal.sh.$(CLUSTER).out
error  = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/inference_run1_signal.sh.$(CLUSTER).err
log    = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/inference_run1_signal.sh.$(CLUSTER).log
request_gpus = 1
+MaxRuntime = 172800
notification = Always
queue

