executable = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/make_graphs_edge.sh
error  = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/make_graphs_edge.$(CLUSTER).err
log    = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/make_graphs_edge.$(CLUSTER).log
output = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/make_graphs_edge.$(CLUSTER).out
request_gpus = 0
+MaxRuntime = 86400
notification = Always
queue
