executable = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/occlusion_analysis.sh
output = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/occlusion_analysis.$(CLUSTER).out
error  = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/occlusion_analysis.$(CLUSTER).err
log    = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/occlusion_analysis.$(CLUSTER).log
request_gpus = 1
request_memory = 16000MB
+MaxRuntime = 172800
notification = Always
queue
