executable = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/optuna_gnn_transformer.sh
output = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/optuna_gnn_transformer.$(CLUSTER).out
error  = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/optuna_gnn_transformer.$(CLUSTER).err
log    = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/optuna_gnn_transformer.$(CLUSTER).log
request_gpus = 1
+MaxRuntime = 604800
notification = Always
queue
