executable = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/train_gnn_transformer_noedge.sh
output = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/train_gnn_transformer_noedge.$(CLUSTER).out
error  = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/train_gnn_transformer_noedge.$(CLUSTER).err
log    = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/train_gnn_transformer_noedge.$(CLUSTER).log
request_gpus = 1
+MaxRuntime = 86400
notification = Always
queue
