executable = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/tsne_analysis.sh
output = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/tsne_analysis.$(CLUSTER).out
error  = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/tsne_analysis.$(CLUSTER).err
log    = /vols/sbn/uboone/ll4420/dark_tridents_wspace/DM-GNN/condor/logs/tsne_analysis.$(CLUSTER).log
request_gpus = 1
+MaxRuntime = 7200
notification = Always
queue
